server:
  port: 8888
# DataSource Config
spring:
  redis:
  main:
    allow-bean-definition-overriding: true
#  security:
#    user:
#      name: user
#      password: password
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER # 解决Failed to start bean ‘documentationPluginsBootstrapper问题
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.106.222.90:3306/db_system?useUnicode=true&useSSL=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: mysql
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
config:
  jwt:
    # 加密秘钥
    secret: f4e2e52034348f86b67cde581c0f9eb5
    # token有效时长，7天，单位秒
    expire: 604800
    header: Authorization